---
namespace: clusterbook

configmaps:
  homerun-demo-pitcher:
    LOAD_CONFIG_FROM: cr
    CONFIG_LOCATION: default #namespace
    CONFIG_NAME: networks-labul #resource-name
    SERVER_PORT: "50051"

deployment:
  name: clusterbook
  labels:
    app: clusterbook
  selectorLabels:
    app: clusterbook
  allowPrivilegeEscalation: "false"
  privileged: "false"
  runAsNonRoot: "true"
  readOnlyRootFilesystem: "true"
  serviceAccount: clusterbook
  ports:
    app-port:
      containerPort: 50051
      protocol: TCP
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
  containers:
    clusterbook:
      image: ghcr.io/stuttgart-things/clusterbook/clusterbook-5f3bb9105a15fafb0e52842968611a61@sha256
      replicaCount: 1
      imagePullPolicy: Always
      tag: 8d4934eaaedf30f71fe73255d624ef6ddb5d92c3bc13273aa1988290c5d005ff
      securityContext:
        capabilities: {}

services:
  clusterbook:
    labels:
      app: clusterbook
    ports:
      - name: grpc-port
        protocol: TCP
        value: 50051
        expose:
          service:
            type: ClusterIP
            port: 80
    selectorLabels:
      app: clusterbook


# RBAC
serviceAccounts:
  clusterbook:
    labels:
      app: clusterbook
roles:
  clusterbook:
    labels:
      app: clusterbook
    rules:
      - apiGroups:
          - ""
        resources:
          - pods
        verbs:
          - get
          - list
          - watch
          - create
roleBindings:
  clusterbook:
    labels:
      app: clusterbook
    roleRef:
      kind: Role
      name: clusterbook
      apiGroup: rbac.authorization.k8s.io
    subjects:
      - kind: ServiceAccount
        name: clusterbook
        namespace: clusterbook
clusterRoles:
  list-all-namespaces:
    labels:
      app: clusterbook
    rules:
      - apiGroups:
          - ""
        resources:
          - namespaces
        verbs:
          - get
          - list
clusterRoleBindings:
  list-all-namespaces-clusterbook:
    roleRef:
      kind: ClusterRole
      name: list-all-namespaces
      apiGroup: rbac.authorization.k8s.io
    subjects:
      - kind: ServiceAccount
        name: clusterbook
        namespace: clusterbook
