---
namespace: clusterbook

test:
  name: clusterbook-grpc-smoketest
  serviceAddr: "clusterbook-service.clusterbook.svc.cluster.local:80"
  #value: "clusterbook.cd43.sthings-pve.labul.sva.de:443"
  imageUrl: ghcr.io/stuttgart-things/clusterbook-client/client-62608e08adc29a8d6dbc9754e659f125@sha256
  imageTag: fd5772746a61d45389d0810a232748d6b3f63ecdb9e08340dad4029ac0167b46
  secureConnection: "false"

configmaps:
  homerun-demo-pitcher:
    LOAD_CONFIG_FROM: cr
    CONFIG_LOCATION: clusterbook #namespace
    CONFIG_NAME: networks-labul #resource-name
    SERVER_PORT: "50051"

deployment:
  name: clusterbook
  labels:
    app: clusterbook
  selectorLabels:
    app: clusterbook
  allowPrivilegeEscalation: "false"
  privileged: "false"
  runAsNonRoot: "true"
  readOnlyRootFilesystem: "true"
  serviceAccount: clusterbook
  ports:
    app-port:
      containerPort: 50051
      protocol: TCP
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
  containers:
    clusterbook:
      image: ghcr.io/stuttgart-things/clusterbook/clusterbook-5f3bb9105a15fafb0e52842968611a61@sha256
      replicaCount: 1
      imagePullPolicy: Always
      tag: 56bacc3eda41ab2536e7639b39019e6fa4b1c4e305d712045de89f370fc71197
      securityContext:
        capabilities: {}

services:
  clusterbook:
    labels:
      app: clusterbook
    ports:
      - name: grpc-port
        protocol: TCP
        value: 50051
        expose:
          service:
            type: ClusterIP
            port: 80
    selectorLabels:
      app: clusterbook


# RBAC
serviceAccounts:
  clusterbook:
    labels:
      app: clusterbook
roles:
  clusterbook:
    labels:
      app: clusterbook
    rules:
      - apiGroups:
          - github.stuttgart-things.com
        resources:
          - networkconfigs
        verbs:
          - get
          - list
          - watch
          - create
          - update
roleBindings:
  clusterbook:
    labels:
      app: clusterbook
    roleRef:
      kind: Role
      name: clusterbook
      apiGroup: rbac.authorization.k8s.io
    subjects:
      - kind: ServiceAccount
        name: clusterbook
        namespace: clusterbook
