---
defaultBaseImage: ghcr.io/stuttgart-things/sthings-alpine:1.23
builds:
  - id: clusterbook
    dir: .
    main: main.go
    ldflags:
      - -s -w -X github.com/stuttgart-things/clusterbook/internal.version={{.Git.Tag}}
      - -s -w -X github.com/stuttgart-things/clusterbook/internal.date={{.Date}}
      - -s -w -X github.com/stuttgart-things/clusterbook/internal.commit={{.Git.ShortCommit}}
