---
defaultBaseImage: ghcr.io/stuttgart-things/sthings-alpine:1.23

labels:
  org.opencontainers.image.source: https://github.com/stuttgart-things/clusterbook

builds:
  - id: machineshop
    dir: .
    main: main.go
    ldflags:
      - -s -w -X github.com/stuttgart-things/clusterbook/cmd.version={{.Git.Tag}}
      - -s -w -X github.com/stuttgart-things/clusterbook/cmd.date={{.Date}}
      - -s -w -X github.com/stuttgart-things/clusterbook/cmd.commit={{.Git.ShortCommit}}
