---
version: 3
vars:
  PROJECT_NAME:
    sh: echo ${PWD##*/}
  PROTO_DIR:
    sh: find . -type f -name "*.proto" -exec dirname {} \; | sort | uniq

tasks:
  proto:
    desc: Generate Go code from proto
    cmds:
      - protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative {{ .PROTO_DIR }}/*.proto
