apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: networkconfigs.github.stuttgart-things.com
spec:
  group: github.stuttgart-things.com
  names:
    kind: NetworkConfig
    listKind: NetworkConfigList
    plural: networkconfigs
    singular: networkconfig
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                networks:
                  type: object
                  additionalProperties:
                    type: array
                    items:
                      type: string