---
environments:
  dev:
    values:
      - env/defaults.yaml
      - env/{{ .Environment.Name }}.yaml

releases:
  - name: clusterbook
    chart: ./clusterbook
    installed: true
    namespace: clusterbook
    values:
      - "values/clusterbook.yaml.gotmpl"

helmDefaults:
  verify: false
  wait: true
  timeout: 600
  recreatePods: false
  force: true
