---
name: Build clusterbook
on:
  workflow_dispatch:
  push:
    branches:
      - '*'
  pull_request:
    types: [opened, reopened]

jobs:
  Validate-Golang:
    name: Valdiate Golang
    uses: stuttgart-things/stuttgart-things/.github/workflows/call-golang-validation.yaml@main
    with:
      module-name: clusterbook
      environment-name: k8s
      runs-on: ghr-clusterbook-skyami-cicd
      golint-version: v1.61.0-alpine
      golang-version: "1.23.1"
      accept-linterrors: false
      accept-failedtests: false
      timeout-minutes: 15m

  Image-Build:
    name: Build image w/ ko
    needs: Validate-Golang
    uses: stuttgart-things/stuttgart-things/.github/workflows/call-ko-build.yaml@main
    with:
      environment-name: k8s
      runs-on: ghr-clusterbook-skyami-cicd
      registry-repo: registry.homerun-dev.sthings-vsphere.labul.sva.de
      module-name: github.com/stuttgart-things/clusterbook
      registry: registry.homerun-dev.sthings-vsphere.labul.sva.de
      vault-path-username: apps/data/build-reg:username
      vault-path-password: apps/data/build-reg:password
    secrets: inherit
