---
name: Validate & Build clusterbook service
on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/**'
      - 'fix/**'
  pull_request:
    types: [opened, reopened]

jobs:
  validate-golang:
    name: Valdiate Golang
    uses: stuttgart-things/github-workflow-templates/.github/workflows/call-golang-validation.yaml@main #go-1.23.1
    with:
      module-name: machineshop
      environment-name: k8s
      runs-on: ghr-clusterbook-skyami-cicd
      golint-version: v1.64.6-alpine
      golang-version: "1.24.0"
      accept-linterrors: true
      accept-failedtests: true
    secrets: inherit  #pragma: allowlist secret
